# Use postgres/example user/password credentials
version: '3.7'

services:

  db:
    image: timescale/timescaledb:latest-pg12
    restart: always
    environment:
      - POSTGRES_USER=dogata
      - POSTGRES_DB=stocks_trending
      - POSTGRES_PASSWORD=dogaLoca22
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

    ports:
      - 5436:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
